#include <iostream>
#include <string>
using namespace std;

int main() {
    string text = "Capybaras make great pets, and the laws against owning them should be reconsidered. Capybaras are a dog-sized animal with coarse fur, native to eastern South America. They are known across the internet as the friendliest animal on the planet, but there are a lot of misinformation about them as pets. They are considered an exotic animal, so a lot of legal restrictions prevent people from owning them as pets, but it is time to reevaluate these laws. \n For one thing, capybaras are rodents—the largest rodents in the world, actually—and plenty of rodents are already normalized as pets. Capybaras are closely related to guinea pigs and chinchillas, both of which are popular pets, and more distantly related to mice and rats, another common type of pet. In nature, most rodents (including capybaras) are social animals and live in groups, which makes them accustomed to life as a pet. \n There are a lot of prevalent myths about capybaras that dissuade people from owning them, but most of these are unfounded. For example, people assume capybaras smell bad, but this is not true; their special fur actually resists odor. Another myth is that they are messy, but in reality, capybaras do not shed often and can even be litter-trained! One rumor based in truth is that they can be destructive and chew on their owners things, but so can dogs, and dogs are one of the most common pets we have. \n The one reasonable criticism for keeping capybaras as pets is that they are high-maintenance. Capybaras require lots of space to run around and are prone to separation anxiety if owners are gone most of the day. Moreover, capybaras are semi-aquatic, so it is best for them to have a pool to swim in. However difficult these special conditions are to meet, they are all still doable; as with all pets, the owners should simply commit to these prerequisites before getting one. \n All in all, the advantages of capybaras as pets outweigh the cons. As rodents, they are social and trainable, and many of the deterrent myths about them are untrue. Even the extra maintenance they require is still manageable. If capybaras are illegal to own where you live, contact your local lawmakers and petition them to reconsider these laws. You will see first-hand just why the internet has fallen in love with this “friend-shaped” animal!";
    int  paragraphs = countParagraphs(text);
    cout << "Number of paragraphs in the text: " << paragraphs << std::endl;
    return 0;
}
